@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjczYzMwMDMzY2Q2ZmYwMGNjODU5YSIsInJvbGUiOiJzdXBlckFkbWluIiwiaWF0IjoxNjg5NzMwMTU1LCJleHAiOjE2ODk3NTE3NTV9.7fCa8_f1tQ-HxZQcPOfMUghnMLBOWYQUWpTNOHp5ImM

@guestAuthToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjVlMTMyMjNjNTM2MWRkMjE4NzQzZiIsInJvbGUiOiJndWVzdCIsImlhdCI6MTY4OTY1NTQ0NCwiZXhwIjoxNjg5Njc3MDQ0fQ.dH2ZZCfwNkHgyJfZ1UDA8FWK4xN4SsIoOKD_9TKZXwM

@guest1AuthToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0YjVlMTMyMjNjNTM2MWRkMjE4NzQzZiIsInJvbGUiOiJndWVzdCIsImlhdCI6MTY4OTY0MTI2NiwiZXhwIjoxNjg5NjYyODY2fQ.jnICB22pi1uk_RcnlRMirFIRq3YBZ6U60w9vMDXvAdc

@guest2AuthToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJndWVzdDMiLCJsYXN0TmFtZSI6Imd1ZXN0MyIsInBhc3N3b3JkIjoiJDJiJDEwJGJ5b0J0M3dwRTZQYWtFNVhxY3JIaGV2RkhjLzNQeXRMMU9kbkg2TEdQMVZyeS9pSUtZZ3RTIiwicGhvbmVOdW1iZXIiOjMzMzMzMzMzLCJyb2xlIjoiZ3Vlc3QiLCJ2ZXJpZmllZCI6ZmFsc2UsIl9pZCI6IjYyMDQzZGFiOWQzNjFiOTY4ZjhmMDQxYyIsImlhdCI6MTY0NDQ0NTA5OSwiZXhwIjoxNjQ1MDQ5ODk5fQ.DUdKiCe6pUyCM1o4QzleamucJH20FG4oaKgde22B3qA

### Create Game
POST {{$dotenv CLIENT_SERVER_URL}}/game/creategame HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{

}

### Start Game
POST {{$dotenv CLIENT_SERVER_URL}}/game/startgame HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{

}


### Close Game
POST {{$dotenv CLIENT_SERVER_URL}}/game/closegame HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{

}


### Participate In Game 1
POST {{$dotenv CLIENT_SERVER_URL}}/game/participateingame HTTP/1.1
Authorization: bearer {{guestAuthToken}}
content-type: application/json

{
     "userId" : "64b438a1eaa7436070075dae"
}

### Participate In Game 2
POST {{$dotenv CLIENT_SERVER_URL}}/game/participateingame HTTP/1.1
Authorization: bearer {{guest1AuthToken}}
content-type: application/json

{
     "userId" : "64b5e13223c5361dd218743f"
}

### Get Game
POST  {{$dotenv CLIENT_SERVER_URL}}/game/getgame HTTP/1.1
Authorization: bearer {{guestAuthToken}}
content-type: application/json 

{
    "id" : "64b438a1eaa7436070075dae"
}

### Guest 1 Answer
POST {{$dotenv CLIENT_SERVER_URL}}/game/guestanswer HTTP/1.1
Authorization: bearer {{guestAuthToken}}
content-type: application/json 

{
    "userId" : "64b438a1eaa7436070075dae",
     "answer":"yes"
}

### Guest 2 Answer
POST {{$dotenv CLIENT_SERVER_URL}}/game/guestanswer HTTP/1.1
Authorization: bearer {{guest1AuthToken}}
content-type: application/json 

{
    "userId" :"64b5e13223c5361dd218743f",
     "answer":"no"
}
### Host Answer
POST {{$dotenv CLIENT_SERVER_URL}}/game/hostanswer HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{
     "answer":"yes"
}

### Get Game
GET {{$dotenv CLIENT_SERVER_URL}}/game/stats HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

### Get Game Winners
GET {{$dotenv CLIENT_SERVER_URL}}/game/gameWinner HTTP/1.1
content-type: application/json 

{
    "gameId" : "64b616337094acdef4821a95",
    "userId" : "64b438a1eaa7436070075dae"
}

### Lock Answers
GET {{$dotenv CLIENT_SERVER_URL}}/game/lockanswers HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

### Get token
POST {{$dotenv CLIENT_SERVER_URL}}/user/refresh HTTP/1.1
content-type: application/json 

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im9vVm9vIiwicm9sZSI6Imd1ZXN0IiwiaWF0IjoxNjM4NDEwOTM3fQ.HWqicVUigaqkT33HZ_T6K_Z0L5_VcwPTymrBSuD0D5Y"
}

### Send Message
POST {{$dotenv CLIENT_SERVER_URL}}/notice/sendmessage HTTP/1.1
content-type: application/json 
Authorization: bearer {{authToken}}

{
    "email": "aymxxen@gmail.com",
    "password": "123456"
}

  
### Get token
POST {{$dotenv CLIENT_SERVER_URL}}/user/refresh HTTP/1.1
content-type: application/json 

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtcGxlIiwiZW1haWwiOiJheW1kZW5AZ21haWwuY29tIiwicm9sZSI6Imd1ZXN0IiwiaWF0IjoxNjM3MzY4MDgwfQ.liVHRcuJV15rAG2EM9cr3MQVTiczpZ7cde2o1XJJ0yk"
}

### Get token
POST {{$dotenv CLIENT_SERVER_URL}}/user/updatefcm HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{
    "firebase_token":"11",
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoic2FtcGxlIiwiZW1haWwiOiJheW1lbkBnbWFpbC5jb20iLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2MzcxNzE5OTB9.E0qtGXQsFvnWk_neRGhpXs5PvYmbEFAShz3EN2sYLPQ"
}

### Get notifications
POST {{$dotenv CLIENT_SERVER_URL}}/user/getallnotices HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{

}

### send message
POST {{$dotenv CLIENT_SERVER_URL}}/user/sendmessage HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{
    "Title":"notification title",
    "Message":"notification message"
}

### send notification
POST https://fcm.googleapis.com/fcm/send
Authorization: key=AAAAKqoUX5k:APA91bGqLpRUQmIiVjbC0uskCp8z2xFWBgQq0PD_21YVA--WZyQjCjXuhzgnM7egSzx8gBPWbKMZR7xJHUQ-ZP8_wFSimeqRG14DOkl9cyP3oYSdIgGg-BUxRT78INttKrEL5SFoZef6
Content-Type: application/json

{
    "registration_ids" : ["dUVtjcSYR9K1K1t_rkCO-G:APA91bFYINVdOyhjubY0Kz0F7qfl-xTPhv_cePgd-v0jldg0hEsIH5GpsEgcE1fmy6-XM58YZ6V7A3fJPDtu43g6CHMjJxG4MaqIz-FIqGVT7URC7xPfn2nE-i8Cs2sTNYsfjNTBxJ4a"], 
    "notification": {
            "body": "Firebase Cloud Message"
        }

}



### Get all users
GET {{$dotenv CLIENT_SERVER_URL}}/user/getall HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{
    "email": "aymen@gmail.com",
    "password": "123456",
    "role": "admin"
}


### Get user by id
POST {{$dotenv CLIENT_SERVER_URL}}/user/getbyid HTTP/1.1
content-type: application/json 

{
    "id": "618fe874b19df5fd81d0518a",
    "email": "aymen@gmail.com",
    "password": "123456"
}

### Get user by email
POST {{$dotenv CLIENT_SERVER_URL}}/user/getbyemail HTTP/1.1
content-type: application/json 

{
    "email": "lex@gmail.com",
    "password": "123456"
}



### Update user
POST {{$dotenv CLIENT_SERVER_URL}}/user/update HTTP/1.1
content-type: application/json 

{
    "id": "618fe7b0b19df5fd81d05188",
    "name": "lex",
    "email": "lex@gmail.com",
    "password": "1234",
    "role": "admin"
}

### Delete user
POST {{$dotenv CLIENT_SERVER_URL}}/user/deletebyid HTTP/1.1
content-type: application/json 
Authorization: bearer {{authToken}}

{
    "id": "619245f3100ba619cc946f1c",
    "name": "sample",
    "email": "aymxxen@gmail.com",         
    "password": "123456",
    "role": "admin"

}

### Delete user by email
POST {{$dotenv CLIENT_SERVER_URL}}/user/deletebyemail HTTP/1.1
content-type: application/json 
Authorization: bearer {{authToken}}

{
    "id": "619246f8100ba619cc946f22",
    "name": "sample",
    "email": "aymxxen@gmail.com",         
    "password": "123456",
    "role": "admin"
}

### Delete all guests
POST {{$dotenv CLIENT_SERVER_URL}}/user/deletebyrole HTTP/1.1
content-type: application/json 

{
    "role": "guest"
}

### Delete all admins
POST {{$dotenv CLIENT_SERVER_URL}}/user/deletebyrole HTTP/1.1
Authorization: bearer {{authToken}}
content-type: application/json 

{
    "role": "admin"
}


### Delete all staff
POST {{$dotenv CLIENT_SERVER_URL}}/user/deletebyrole HTTP/1.1
content-type: application/json 

{
    "role": "staff"
}

### Add friend
POST {{$dotenv CLIENT_SERVER_URL}}/user/addfriend HTTP/1.1
content-type: application/json 
Authorization: bearer {{authToken}}

{
    "friend": "idris@gmail.com"
}

### Get all friends
POST {{$dotenv CLIENT_SERVER_URL}}/user/getfriends HTTP/1.1
content-type: application/json 
Authorization: bearer {{authToken}}

{
    "id": ""
}


### Remove friend
POST {{$dotenv CLIENT_SERVER_URL}}/user/removefriend HTTP/1.1
content-type: application/json 
Authorization: bearer {{authToken}}

{
    "friend": "idris@gmail.com"
}

### send notification
POST {{$dotenv prodUrl}}/game/sendnotification HTTP/1.1
content-type: application/json
Authorization: bearer {{authToken}}

{
    "title": "Noir ou Blanc",
    "body": "vous avez gagné le jeu Noir ou Blanc"
}